

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    #    database-platform: org.hibernate.dialect.PostgresSqlDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgresSqlDialect
      format_sql: true


